<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://clases.formacion.ipartek.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://clases.formacion.ipartek.com" xmlns:intf="http://clases.formacion.ipartek.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://clases.formacion.ipartek.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="randomQuote">
    <complexType/>
   </element>
   <element name="randomQuoteResponse">
    <complexType>
     <sequence>
      <element name="randomQuoteReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="randomQuoteRequest">

      <wsdl:part element="impl:randomQuote" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="randomQuoteResponse">

      <wsdl:part element="impl:randomQuoteResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="DreddSays">

      <wsdl:operation name="randomQuote">

         <wsdl:input message="impl:randomQuoteRequest" name="randomQuoteRequest">

       </wsdl:input>

         <wsdl:output message="impl:randomQuoteResponse" name="randomQuoteResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="DreddSaysSoapBinding" type="impl:DreddSays">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="randomQuote">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="randomQuoteRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="randomQuoteResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="DreddSaysService">

      <wsdl:port binding="impl:DreddSaysSoapBinding" name="DreddSays">

         <wsdlsoap:address location="http://localhost:8080/Adibidea/services/DreddSays"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
